services:
  mongodb:
    image: mongo:7.0
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog-network

  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    ports:
      - "3030:3030"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - blog-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  blog-network:
    driver: bridge